name: My Jobs
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: [self-hosted]

    env:
      CONTAINER_NAME: myappCommandContainer
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t myapp:latest -f ./Dockerfile .

      - name: Stop and Remove Existing Container if Any
        run: |
          CNAME=${{ env.CONTAINER_NAME }}

          # Kiểm tra xem container có tồn tại không
          if [ "$(docker ps -aq -f name=$CNAME)" ]; then
              echo ":: Container $CNAME exists"
              
              # Kiểm tra container có đang chạy không
              if [ "$(docker ps -q -f name=$CNAME)" ]; then
                  echo ":: Stopping running container - $CNAME"
                  docker stop $CNAME
              fi

              echo ":: Removing container - $CNAME"
              docker rm $CNAME
          else
              echo ":: No existing container named $CNAME"
          fi

      - name: Remove Old Docker Image (Optional)
        run: |
          echo ":: Removing old image myapp:latest"
          docker rmi -f myapp:latest || true

      - name: Run New Docker Container
        run: |
          CNAME=${{ env.CONTAINER_NAME }}
          echo ":: Running new container - $CNAME"
          docker run -d -p 8080:8080 --name $CNAME myapp:latest
