name: My Jobs

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: [self-hosted]

    env:
      CONTAINER_NAME: myappCommandContainer

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t myapp:latest -f ./Dockerfile .

      - name: Stop and Remove Existing Container if Any
        run: |
          echo ":: Checking existing container - ${{ env.CONTAINER_NAME }}"
          if [ "$(docker ps -aq -f name=${{ env.CONTAINER_NAME }})" ]; then
              if [ "$(docker ps -aq -f status=exited -f name=${{ env.CONTAINER_NAME }})" ]; then
                  echo ":: Container exists and is exited, removing..."
                  docker rm ${{ env.CONTAINER_NAME }}
              else
                  echo ":: Container exists and is running, stopping and removing..."
                  docker stop ${{ env.CONTAINER_NAME }}
                  docker rm ${{ env.CONTAINER_NAME }}
              fi
          else
              echo ":: No existing container named ${{ env.CONTAINER_NAME }}"
          fi

      - name: Run New Docker Container
        run: |
          echo ":: Running new container - ${{ env.CONTAINER_NAME }}"
          docker run -d -p 8443:8443 \
            --name ${{ env.CONTAINER_NAME }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            -e GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }} \
            myapp:latest
